### ISSUE TITLE
Ch.6 Logic is reversed or ambiguous variable name

### ISSUE THREAD

**Issue by eidosam** [gisaac85/hyf-JavaScript1#2]
I think you are classifying the vehicles into 5 generations, that means `age` in your code doesn't reflect the number of years https://dictionary.cambridge.org/dictionary/english/age but the _generation_ (you still can use `age` for that, but it is ambiguous).

If so, would be better if that is reflected in the variable name, right? 
https://github.com/gisaac85/hyf-JavaScript1/blob/83101bf0e659dbdedf2bf743a1f1e7164a03b10f/week3/Assignment4.js#L150

**Comment by gisaac85** [comment]
I use switch to select age! 
But I didn't understand u !

**Comment by eidosam** [comment]
Sorry for not explaining my point clearly!
If the `vehicle.age = 1` it shows **OLD** while if `vehicle.age = 5` it shows **NEW**
Which one should be newer? 1 year or 5 years?

**Comment by gisaac85** [comment]
You mean I should change age into generation ???

**Comment by gisaac85** [comment]
ok hhhhh i didn't understand well what this step mean by age ... i understood that age is generation .

**Comment by gisaac85** [comment]
in the step example he said that value (1) is : used .... i changed my switch to be more logical .. can u see plz ~?

**Comment by eidosam** [comment]
👍
