### ISSUE TITLE
Ch.10 Data Type confusion 

### ISSUE THREAD

**Issue by eidosam** [gisaac85/hyf-JavaScript1#3]
This variable initialized as an `Array` then used as `String`
https://github.com/gisaac85/hyf-JavaScript1/blob/83101bf0e659dbdedf2bf743a1f1e7164a03b10f/week3/Assignment4.js#L214
Before the function returns run and see

    console.log(typeof jj);

**Comment by gisaac85** [comment]
Ja I feel that it must be string or I should make some changing as it is array.

**Comment by eidosam** [comment]
👍
